version: v2beta1
name: netku-sentinel

dev:
  bot:
    labelSelector:
      app: netku-sentinel-bot
    sync:
    - path: .:/app
      noWatch: true
      disableDownload: true
      printLogs: true
      initialSync: mirrorLocal
      uploadExcludePaths:
        - "**/__pycache__/**"
        - "**/*.pyc"
        - "**/*.pyo"
        - ".*"
        - "venv"
        - "proto"
      onUpload:
        exec:
        - name: pip-install
          command: sh
          args: ["-c", "pip install --user -r /app/requirements.txt"]
          onChange: ["requirements.txt"]
        - name: restart
          command: sh
          args: ["-c", "kill 1 || true"]
          onChange: ["requirements.txt"]

  events:
    labelSelector:
      app: netku-sentinel-events
    sync:
    - path: .:/app
      noWatch: true
      disableDownload: true
      printLogs: true
      initialSync: mirrorLocal
      uploadExcludePaths:
        - "**/__pycache__/**"
        - "**/*.pyc"
        - "**/*.pyo"
        - ".*"
        - "venv"
        - "proto"
      onUpload:
        exec:
        - name: pip-install
          command: sh
          args: ["-c", "pip install --user -r /app/requirements.txt"]
          onChange: ["requirements.txt"]
        - name: restart
          command: sh
          args: ["-c", "kill 1 || true"]
          onChange: ["requirements.txt"]

  admin:
    labelSelector:
      app: netku-sentinel-admin
    sync:
    - path: .:/app
      noWatch: true
      disableDownload: true
      printLogs: true
      initialSync: mirrorLocal
      uploadExcludePaths:
        - "**/__pycache__/**"
        - "**/*.pyc"
        - "**/*.pyo"
        - ".*"
        - "venv"
        - "proto"
      onUpload:
        exec:
        - name: pip-install
          command: sh
          args: ["-c", "pip install --user -r /app/requirements.txt"]
          onChange: ["requirements.txt"]
        - name: restart
          command: sh
          args: ["-c", "kill 1 || true"]
          onChange: ["requirements.txt"]



pipelines:
  dev-bot: |-
    start_dev bot
  dev-events: |-
    start_dev events
  dev-admin: |-
    start_dev admin
