# --- COMMON ---
container:
  image: registry.infanasotku.com:5501/netku/netku-sentinel
  tag: latest
environment: prod
name: netku-sentinel
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

config:
  POSTGRES__DB_NAME: netku
  REDIS__DB: "0"
  REDIS__PORT: "6381"
  RABBIT_PROXY_VHOST: "/proxy"
  RABBIT__USERNAME: "sentinel"
  BOT__URL: "https://sentinel.infanasotku.com/process_message"

# --- BOT ---
bot:
  version: "0.1.0"
  replicas: 2
  container:
    name: netku-sentinel-bot
    port: 5100
    args:
      [
        "app.entrypoints.bot:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5100",
      ]
  ingress:
    host: sentinel.infanasotku.com
    path: /

# --- EVENTS ---
events:
  version: "0.1.0"
  replicas: 1
  container:
    name: netku-sentinel-events
    port: 5101
    args:
      [
        "app.entrypoints.events:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5101",
      ]

# --- ADMIN ---
admin:
  version: "0.1.0"
  replicas: 1
  container:
    name: netku-sentinel-admin
    port: 5100
    args:
      [
        "app.entrypoints.admin:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5102",
      ]
  ingress:
    host: admin.sentinel.infanasotku.com
    path: /
