environment: dev
container:
  tag: dev
securityContext:
  runAsNonRoot: false
  runAsUser: 0

config:
  POSTGRES__DB_NAME: netku_debug
  REDIS__DB: "0"
  REDIS__PORT: "6382"
  RABBIT_PROXY_VHOST: "/test/proxy"
  RABBIT__USERNAME: "test"
  BOT__URL: "https://dev.sentinel.infanasotku.com/process_message"

# --- BOT ---
bot:
  replicas: 1
  ingress:
    host: dev.sentinel.infanasotku.com
  container:
    args:
      [
        "app.entrypoints.bot:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5100",
        "--reload"
      ]

# --- EVENTS ---
events:
  replicas: 1
  container:
    args:
      [
      "app.entrypoints.events:app",
      "--workers",
      "1",
      "--host",
      "0.0.0.0",
      "--port",
      "5101",
      "--reload"
    ]

# --- ADMIN ---
admin:
  replicas: 1
  container:
    args:
      [
        "app.entrypoints.admin:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5102",
        "--reload"
      ]
