apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bot.container.name }}-{{ .Values.environment }}
  annotations:
    infanasotku.com: "Infanasotku software engineier"

spec:
  replicas: {{ .Values.bot.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.bot.container.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.bot.container.name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.bot.version }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}

    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}

      {{/* ---------- DEV-ONLY ---------- */}}
      {{- if eq .Values.environment "dev" }}
      volumes:
      - name: dev-volume
        emptyDir: {}

      initContainers:
        - name: seed-code
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "▶ seeding code into volume"
              cp -a /app/. /workspace/
          volumeMounts:
            - name: dev-volume
              subPath: src
              mountPath: /workspace
      {{- end }}

      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
        - name: {{ .Values.bot.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always

          command: ["uvicorn"]
          args: {{ .Values.bot.container.args | toJson }}
          ports:
            - containerPort: {{ .Values.bot.container.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-config
            - secretRef:
                name: {{ .Values.name }}-secrets

          {{- if ne .Values.environment "dev" }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.bot.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.bot.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          {{- end }}

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            capabilities:
              drop: ["ALL"]

          {{/* ---------- DEV-ONLY ---------- */}}
          {{- if eq .Values.environment "dev" }}
          volumeMounts:
          - mountPath: /app
            name: dev-volume
            subPath: src
          - mountPath: /root/.local
            name: dev-volume
            subPath: site
          {{- end }}

      imagePullSecrets:
        - name: regcred
