apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.bot.ingress.host }}
    http:
      paths:
      - path: {{ .Values.bot.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bot.container.name }}-{{ .Values.environment }}-service
            port:
              number: {{ .Values.bot.container.port }}
