apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
type: Opaque
stringData:
{{- $secrets := .Files.Get "temp-secrets.yaml" | fromYaml }}
{{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val }}
{{- end }}
