name: load-pr-data

on:
  workflow_call:
    outputs:
      pr_data:
        description: "Pull request data"
        value: ${{ jobs.pr-data.outputs.pr_data }}

jobs:
  pr-data:
    name: Load PR data
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      pr_data: ${{ steps.get_pr_data.outputs.result }}

    steps:
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
